name: MirrorBot Environment

on:
  push:
  workflow_dispatch:
   

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Cleanup workspace
        uses: rokibhasansagar/slimhub_actions@main

      - name: step 3
        run: |
          git config --global user.email ${{ secrets.GHMAIL }}
          git config --global user.name ${{ secrets.GHUSER }}
          git config --global credential.helper store
          echo "https://${{ secrets.GHUSER }}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
      - name: step 4
        run: |
          git clone https://${{ secrets.GH_TOKEN }}@github.com/${{ secrets.GHUSER }}/${{ secrets.REPO }} source
      - name: step 5
        run: |
          cd source || exit 1
          docker container prune --force || true
          docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t mirror-bot
      - name: Run step
        continue-on-error: true
        timeout-minutes: 500
        run: |
          docker run --privileged --rm -i mirror-bot
      - name: Loop 
        continue-on-error: true
        run: |
          git clone https://${{ secrets.GH_TOKEN }}@github.com/${GITHUB_REPOSITORY} loop
          cd loop || exit 1
          git commit --allow-empty -m "Workflow: Loop"
          git push -f
